.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..

.TH robustirc-bridge 1 "JANUARY 2015" Linux "User Manuals"

.SH NAME
robustirc-bridge \- bridge between IRC and RobustIRC

.SH SYNOPSIS
.B robustirc-bridge
.RB [\|\-listen
.IR address \|]
.RB [\|\-network
.IR address \|]
.RB [\|\-socks
.IR address \|]
.RB [\|\-tls_ca_file
.IR path \|]
.RB [\|\-motd_path
.IR path \|]

.SH DESCRIPTION
.B robustirc-bridge
allows you to connect to a RobustIRC network using your regular IRC client
(such as irssi, WeeChat, XChat, etc).

It can be used as a SOCKS proxy for IRC clients which support SOCKS proxies,
or it can be run for a specific RobustIRC network, in which case it will
listen on a port (localhost:6667 by default) and talk IRC.

.SH OPTIONS
.TP
.BI \-listen\  address \fR
Listen on the provided address for IRC connections (in host:port format, see
also http://golang.org/pkg/net/#Dial for more details).

\fB-network\fR must also be specified for \fB-listen\fR to have any effect.

.TP
.BI \-network\  address \fR
When accepting new connections on the port specified by \fB-listen\fR, to which network should they be bridged? This is a DNS name such as "robustirc.net". The servers to connect to will be resolved by resolving the _robustirc._tcp SRV record for that DNS name.

If \fB-network\fR is unspecified, \fB-listen\fR will not be used, and only the \fB-socks\fR functionality will be provided.

.TP
.BI \-socks\  address \fR
Listen on the provided address for SOCKS connections (in host:port format, see
also http://golang.org/pkg/net/#Dial for more details).

.TP
.BI \-motd_path\  path \fR
Path to a text file containing the message of the day (MOTD) to prefix to the network MOTD.

The default MOTD warns people that they should run their own bridge instead of
connecting, and you are expected to specify \fB-motd_path=\fR (i.e. empty) when
starting the bridge in a scenario where you are the only user or all users run
their IRC client on the same machine as the bridge.

.TP
.BI \-tls_ca_file\  path \fR
Use the specified file as trusted CA instead of the system CAs. Useful for
testing.

.SH AUTHOR
Michael Stapelberg
