name: Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Debian oldstable (bullseye) has Go 1.15
        go: [ '1.24', '1.23', '1.22', '1.21', '1.20', '1.19', '1.18', '1.17', '1.16', '1.15' ]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Ensure all files were formatted as per gofmt
      env:
        GOPATH: /home/runner/work/bridge/go
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: Run tests
      env:
        GOPATH: /home/runner/work/bridge/go
      run: |
        go install github.com/robustirc/bridge/robustirc-bridge || go get github.com/robustirc/bridge/robustirc-bridge
